# Generated by Django 5.2.5 on 2025-12-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioKelpApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
