# Generated by Django 5.2.6 on 2025-12-19 14:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioKelpApp', '0002_cliente_apellido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='alerta',
            old_name='fecha_creacion',
            new_name='creada_en',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='id_alerta',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='tipo_alerta',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='alerta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='leida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alerta',
            name='nivel',
            field=models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('critical', 'Crítica')], default='warning', max_length=10),
        ),
        migrations.AddField(
            model_name='alerta',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='bioKelpApp.especie'),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('cantidad_humedo_kg', models.FloatField(default=0)),
                ('cantidad_seco_kg', models.FloatField(default=0)),
                ('fecha_cosecha', models.DateField(blank=True, null=True)),
                ('fecha_almacenamiento', models.DateField(blank=True, null=True)),
                ('fecha_procesamiento', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='bioKelpApp.especie')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='bioKelpApp.planta')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('produccion', 'Producción'), ('compra', 'Compra externa'), ('consumo', 'Consumo / Salida'), ('ajuste', 'Ajuste'), ('etapa_update', 'Actualización de etapa')], max_length=20)),
                ('cantidad_humedo_kg', models.FloatField(default=0)),
                ('cantidad_seco_kg', models.FloatField(default=0)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='bioKelpApp.especie')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='bioKelpApp.lote')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioKelpApp.permiso')),
            ],
        ),
    ]
