# Generated by Django 5.2.5 on 2025-12-04 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioKelpApp', '0003_especie_planta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_alerta', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='bioKelpApp.stock')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='bioKelpApp.usuario')),
            ],
            options={
                'db_table': 'alerta_stock',
            },
        ),
    ]
