# Generated by Django 5.2.6 on 2025-12-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioKelpApp', '0004_create_groups_permissions'),
        ('bioKelpApp', '0005_create_comercial_permissions'),
    ]

    operations = [
    ]
